export enum CreateVzorekFormEnum {
    DRUH = 'druh',
    POPIS = "popis",
    DOVOZ = "dovoz",
    DOVOZ_DATUM = "dovoz_datum",
    OZNACENI_SVLECKY = "oznaceni_svlecky",
    SBER_SVLECKY_DATUM = "sber_svlecky_datum",
    SBER_SVLECKY_MISTO = "sber_svlecky_misto",
    CISLO_KOTCE = "cislo_kotce",
    ULOZENI_SVLECKY_MISTO = "ulozeni_svlecky_misto",
    OZNACENI_VZORKU_SVLECKY = "oznaceni_vzorku_svlecky",
    PRED_POSL_SVLECENIM_MISTO = "pred_posl_svlecenim_misto",
    PUVODNI_HMOTNOST = "puvodni_hmotnost",
    PRIPRAVA_VZORKU_TYP = "priprava_vzorku_typ",
    PRIPRAVA_VZORKU_KDY = "priprava_vzorku_kdy",
    PRIPRAVA_VZORKU_KDO = "priprava_vzorku_kdo",
    PRIPRAVA_VZORKU_MISTO = "priprava_vzorku_misto",
    PRIPRAVA_VZORKU_OPLACH = "priprava_vzorku_oplach",
    PRIPRAVA_VZORKU_OPLACH_KDY = "priprava_vzorku_oplach_kdy",
    PRIPRAVA_VZORKU_SUSENI = "priprava_vzorku_suseni",
    ULOZENI_VZORKU_DO_ANALYZY_MISTO = "ulozeni_vzorku_do_analyzy_misto",
    ULOZENI_VZORKU_DO_ANALYZY_OBJEKT = "ulozeni_vzorku_do_analyzy_objekt",
    ULOZENI_VZORKU_AKTUALNI = "ulozeni_vzorku_aktualni",
    DODANI_ALBERTOV_DATUM = "dodani_albertov_datum"
}